platform :ios, '6.0'

target :'nbkr-ios' do
  pod "nbkr-ios", :path => "../"
  pod "ReactiveCocoa"
  pod 'libextobjc'
end

target :'nbkr-iosTests' do
  pod 'Specta'
  pod 'Expecta'
  pod 'Nocilla'
  pod 'OCMock'
end