platform :ios, '6.0'


target :'nbkr-ios' do
  pod "nbkr-ios", :path => "../"
end

target :'nbkr-iosTests' do
  pod 'Specta'
  pod 'Expecta'
  pod 'Nocilla'
end

# link_with ['nbkr-ios', 'nbkr-iosTests']
